# GitHub Pages 배포를 위한 워크플로우
# 모든 액션을 검증된 최신 안정화 버전으로 수정하여 오류 문제를 해결합니다.
name: Process Pending Analysis Data

on:
  # 1시간마다 자동으로 실행
  schedule:
    - cron: '0 * * * *'
  # Actions 탭에서 수동으로 실행 가능
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  process-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allow to commit changes to the repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }} # Use a PAT to allow the action to trigger other workflows

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Process Pending Files
        id: process
        run: |
          node -e '
            const fs = require("fs").promises;
            const path = require("path");

            async function run() {
              const pendingDir = "data/pending";
              const mainDataPath = "data/main.json";

              try {
                // Read main data file
                let mainData = {};
                try {
                  const content = await fs.readFile(mainDataPath, "utf-8");
                  mainData = JSON.parse(content);
                  console.log(`Loaded ${mainDataPath} with ${Object.keys(mainData).length} entries.`);
                } catch (e) {
                  console.log(`${mainDataPath} not found or empty, starting fresh.`);
                }

                // Read pending files
                const pendingFiles = await fs.readdir(pendingDir);
                const jsonFiles = pendingFiles.filter(f => f.endsWith(".json"));
                
                if (jsonFiles.length === 0) {
                  console.log("No pending files to process.");
                  return;
                }
                
                console.log(`Found ${jsonFiles.length} pending files to process.`);
                let updated = false;

                for (const file of jsonFiles) {
                  const filePath = path.join(pendingDir, file);
                  try {
                    const pendingContent = await fs.readFile(filePath, "utf-8");
                    const pendingData = JSON.parse(pendingContent);
                    Object.assign(mainData, pendingData);
                    await fs.unlink(filePath); // Delete processed file
                    console.log(`Processed and deleted ${file}.`);
                    updated = true;
                  } catch (e) {
                    console.error(`Error processing file ${file}:`, e);
                  }
                }
                
                if (updated) {
                  await fs.writeFile(mainDataPath, JSON.stringify(mainData, null, 2));
                  console.log(`Successfully updated ${mainDataPath} with new data.`);
                  console.log("::set-output name=updated::true");
                }

              } catch (e) {
                if (e.code === "ENOENT" && e.path === pendingDir) {
                   console.log("Pending directory does not exist, nothing to do.");
                } else {
                  console.error("An error occurred:", e);
                  process.exit(1);
                }
              }
            }
            run();
          '
      
      - name: Commit and push if changed
        if: steps.process.outputs.updated == 'true'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add data/main.json data/pending
          git commit -m "Chore: Process and update analysis data"
          git push

